services:
  db:
    image: postgres:16-alpine
    container_name: school-map-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: school_map_db
      DATABASE_URL: "postgresql://admin:password123@localhost:5433/school_map_db?schema=public"
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
