  # .github/workflows/deploy-frontend.yml
name: Desplegar Frontend

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # ¡ESTE PASO ES EL MAGICO! Le enseña al robot a usar PNPM
      - name: Instalar PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 8 # O la versión de pnpm que usen localmente

      - name: Instalar dependencias
        working-directory: ./frontend
        run: |
          pnpm install # Usamos pnpm en lugar de npm

      - name: Compilar la app
        working-directory: ./frontend
        run: |
          pnpm run build # Esto en Next.js genera la carpeta 'out'

      - name: Subir artefacto de la compilación
        uses: actions/upload-artifact@v4
        with:
          name: app-compilada   
          path: frontend/out

      - name: Descargar artefacto compilado
        uses: actions/download-artifact@v4
        with:
          name: app-compilada
          path: build-temp 

      - name: Copiar archivos al servidor
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22002                              # Puerto SSH custom de tu poli
          source: "build-temp/" 
          target: "~/public_html/"                 # Carpeta destino final del frente