# 5. Subir el artefacto (la carpeta 'out' de Next.js)
      - name: Subir artefacto de la compilación
        uses: actions/upload-artifact@v4
        with:
          name: app-compilada   
          path: frontend/out # Busca la carpeta out dentro de frontend

      # 6. Descargar el artefacto directamente en el directorio raíz del robot
      - name: Descargar artefacto compilado
        uses: actions/download-artifact@v4
        with:
          name: app-compilada
          path: out-clean # Lo descargamos en una carpeta limpia en la raíz

      # 7. Copiar los archivos al servidor del Poli
      - name: Copiar archivos al servidor
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22002
          source: "out-clean/*"      # <-- CORREGIDO: Toma todo el contenido limpio
          strip_components: 1        # <-- MAGIA: Evita que se cree la carpeta "out-clean" en el servidor
          [cite_start]target: "~/public_html/"   # Tu carpeta asignada en el Poli [cite: 189]